### PR TITLE
WIP: Add builds with SonarQube 6.7.1 and 7.0

### PR DESCRIPTION
**Pull request by KengoTODA**
It seems that current test code cannot work with current LTS and latest version.
This PR reproduces this issue on Travis, by introducing build matrix.

### CODE REVIEW

**Comment by h3xstream** [comment]
Not sure.. Why it attempt to contact a Sonar server at this step
```
[INFO] User cache: /home/travis/.sonar/cache
[ERROR] SonarQube server [http://localhost:9000] can not be reached
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.555 s
[INFO] Finished at: 2018-03-10T13:00:26Z
[INFO] Final Memory: 50M/738M
[INFO] ------------------------------------------------------------------------
```
https://travis-ci.org/spotbugs/sonar-findbugs/jobs/351687170#L2731

**Comment by h3xstream** [comment]
SonarQube 7.0 seems to be yet another API change.
```
cannot find symbol
  symbol:   variable CORE_VIOLATION_LOCALE_PROPERTY
  location: interface org.sonar.api.CoreProperties
[INFO] 9 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.122 s
[INFO] Finished at: 2018-03-04T09:14:50Z
[INFO] Final Memory: 38M/702M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.2:testCompile (default-testCompile) on project sonar-findbugs-plugin: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/spotbugs/sonar-findbugs/src/test/java/org/sonar/plugins/findbugs/FindbugsTests.java:[46,37] cannot find symbol
[ERROR]   symbol:   method getResource(java.lang.String)
[ERROR]   location: class org.sonar.test.TestUtils
[ERROR] /home/travis/build/spotbugs/sonar-findbugs/src/test/java/org/sonar/plugins/findbugs/FindbugsSensorTest.java:[76,39] incompatible types: java.io.File cannot be converted to java.nio.file.Path
[ERROR] /home/travis/build/spotbugs/sonar-findbugs/src/test/java/org/sonar/plugins/findbugs/FindbugsPluginTest.java:[33,66] incompatible types: org.sonar.api.utils.Version cannot be converted to org.sonar.api.SonarRuntime
[ERROR] /home/travis/build/spotbugs/sonar-findbugs/src/test/java/org/sonar/plugins/findbugs/FindbugsConfigurationTest.java:[57,33] incompatible types: java.io.File cannot be converted to java.nio.file.Path
[ERROR] /home/travis/build/spotbugs/sonar-findbugs/src/test/java/org/sonar/plugins/findbugs/FindbugsConfigurationTest.java:[59,16] org.sonar.api.config.Settings is abstract; cannot be instantiated
[ERROR] /home/travis/build/spotbugs/sonar-findbugs/src/test/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocatorTest.java:[105,59] incompatible types: java.lang.String cannot be converted to org.sonar.api.batch.fs.internal.DefaultIndexedFile
[ERROR] /home/travis/build/spotbugs/sonar-findbugs/src/test/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocatorTest.java:[114,59] incompatible types: java.lang.String cannot be converted to org.sonar.api.batch.fs.internal.DefaultIndexedFile
[ERROR] /home/travis/build/spotbugs/sonar-findbugs/src/test/java/org/sonar/plugins/findbugs/FindbugsExecutorTest.java:[107,25] org.sonar.api.config.Settings is abstract; cannot be instantiated
[ERROR] /home/travis/build/spotbugs/sonar-findbugs/src/test/java/org/sonar/plugins/findbugs/FindbugsExecutorTest.java:[108,40] cannot find symbol
[ERROR]   symbol:   variable CORE_VIOLATION_LOCALE_PROPERTY
[ERROR]   location: interface org.sonar.api.CoreProperties
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.2:testCompile (default-testCompile) on project sonar-findbugs-plugin: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1038)
    at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:172)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by h3xstream** [comment]
I have made the needed fix to have compatibility with the latest version.
The APIs that were changed are classes from sonar-java that were reused in the test scope.

Theoretically, it would be possible to compile a 5.6 version by skipping the compilation of tests or create a different set of tests. I don't think it's worth the trouble.

@KengoTODA If you are OK with it, I will comment the travis-ci line for version 5.6. It will make the build pass. https://travis-ci.org/spotbugs/sonar-findbugs/builds/352480972

**Comment by h3xstream** [comment]
Two changes:

### 5.6 Removal

5.6 is no longer supported  https://groups.google.com/forum/#!msg/sonarqube/JzgetifU9ik/VruCki39DAAJ / http://archive.is/RhM7g
Took me some time to find something official.

### Lower version for Sonar-Java requirement

I did a test with the latest download available. It includes sonar-java `5.1.0.13090`. If anybody is using those for docker images or anything that automatically provision the SpotBugs plugin it will failed.
I saw this behavior by installing the build manually with the latest version.
In the end, the requirement is only for a certain level of compatibility with some API. We are not using heavily the code from sonar-java.
